# ==============================================================================
# Merged Lakeflow Source: zoho_crm
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from datetime import datetime
from decimal import Decimal
from typing import Any, Iterator
import json

from .handlers import (
    ModuleHandler,
    RelatedHandler,
    SettingsHandler,
    SubformHandler,
)
from .zoho_client import ZohoAPIClient
from pyspark.sql import Row
from pyspark.sql.datasource import DataSource, DataSourceReader, SimpleDataSourceStreamReader
from pyspark.sql.types import *
import base64
import logging


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # sources/zoho_crm/zoho_crm.py
    ########################################################

    logger = logging.getLogger(__name__)


    class LakeflowConnect:
        """
        Zoho CRM connector for Lakeflow/Databricks.

        This class serves as the main entry point and orchestrator for the connector.
        It delegates actual work to specialized handlers for different table types.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the Zoho CRM connector with connection-level options.

            Expected options:
                - client_id: OAuth Client ID from Zoho API Console
                - client_value_tmp: OAuth Client Secret from Zoho API Console
                - refresh_value_tmp: Long-lived refresh token obtained from OAuth flow
                - base_url (optional): Zoho accounts URL for OAuth.
                  Defaults to https://accounts.zoho.com
                  Examples: US=accounts.zoho.com, EU=accounts.zoho.eu,
                  IN=accounts.zoho.in, AU=accounts.zoho.com.au
                - initial_load_start_date (optional): Starting point for the first sync.
                  If omitted, syncs all historical data.

            Note: To obtain the refresh_value_tmp, follow the OAuth setup guide in
            sources/zoho_crm/configs/README.md
            """
            # Validate required options
            client_id = options.get("client_id")
            client_secret = options.get("client_value_tmp")
            refresh_token = options.get("refresh_value_tmp")

            if not all([client_id, client_secret, refresh_token]):
                raise ValueError("Zoho CRM connector requires 'client_id', 'client_value_tmp', " "and 'refresh_value_tmp' in the UC connection")

            # Store configuration
            self.initial_load_start_date = options.get("initial_load_start_date")
            accounts_url = options.get("base_url", "https://accounts.zoho.com")

            # Initialize API client
            self._client = ZohoAPIClient(
                client_id=client_id,
                client_secret=client_secret,
                refresh_token=refresh_token,
                accounts_url=accounts_url,
            )

            # Initialize handlers
            self._module_handler = ModuleHandler(self._client)
            self._settings_handler = SettingsHandler(self._client)
            self._subform_handler = SubformHandler(self._client, self._module_handler)
            self._related_handler = RelatedHandler(self._client)

            # Build derived tables lookup
            self._derived_tables = self._build_derived_tables_map()

        def _build_derived_tables_map(self) -> dict[str, tuple[object, dict]]:
            """
            Build a mapping of derived table names to their handlers and configs.

            Derived tables are non-module tables that require special handling:
            - Settings tables (Users, Roles, Profiles)
            - Subform tables (Quoted_Items, etc.)
            - Junction/related tables (Campaigns_Leads, etc.)

            Returns:
                Dictionary mapping table name to (handler, config) tuple
            """
            derived = {}

            # Settings tables
            for name, config in SettingsHandler.get_tables().items():
                derived[name] = (self._settings_handler, {"type": "settings", **config})

            # Subform tables
            for name, config in SubformHandler.get_tables().items():
                derived[name] = (self._subform_handler, {"type": "subform", **config})

            # Related tables
            for name, config in RelatedHandler.get_tables().items():
                derived[name] = (self._related_handler, {"type": "related", **config})

            return derived

        def _get_handler_and_config(self, table_name: str) -> tuple[object, dict]:
            """
            Get the appropriate handler and configuration for a table.

            Returns:
                Tuple of (handler, config) for the table
            """
            if table_name in self._derived_tables:
                return self._derived_tables[table_name]

            # Standard module
            return self._module_handler, {"initial_load_start_date": self.initial_load_start_date}

        def list_tables(self) -> list[str]:
            """
            List names of all tables (modules) supported by this connector.

            Uses the Modules API to dynamically discover available modules,
            plus derived tables for settings, subforms, and junction tables.

            Returns:
                Sorted list of table names
            """
            # Get standard CRM modules
            modules = self._module_handler.get_modules()
            table_names = [m["api_name"] for m in modules]

            # Add derived tables
            table_names.extend(self._derived_tables.keys())

            return sorted(table_names)

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            """
            Fetch the schema of a table dynamically from Zoho CRM.

            Args:
                table_name: Name of the table to get schema for
                table_options: Additional options for accessing the table

            Returns:
                Spark StructType representing the table schema
            """
            self._validate_table_exists(table_name)
            handler, config = self._get_handler_and_config(table_name)
            return handler.get_schema(table_name, config)

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            """
            Fetch the metadata of a table.

            Args:
                table_name: Name of the table
                table_options: Additional options for accessing the table

            Returns:
                Dictionary containing:
                    - primary_keys: List of primary key column names
                    - cursor_field: (optional) Field name for incremental loading
                    - ingestion_type: "snapshot", "cdc", "cdc_with_deletes", or "append"
            """
            self._validate_table_exists(table_name)
            handler, config = self._get_handler_and_config(table_name)
            return handler.get_metadata(table_name, config)

        def read_table(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """
            Read records from a Zoho CRM table.

            Supports incremental reads using Modified_Time cursor and pagination.
            Routes to specialized handlers based on table type.

            Args:
                table_name: Name of the table to read
                start_offset: Offset to start reading from (for incremental loads)
                table_options: Additional options for accessing the table

            Returns:
                Tuple of (records_iterator, next_offset)
            """
            self._validate_table_exists(table_name)
            handler, config = self._get_handler_and_config(table_name)
            return handler.read(table_name, config, start_offset)

        def _validate_table_exists(self, table_name: str) -> None:
            """
            Validate that a table exists and is supported.

            Args:
                table_name: Name of the table to validate

            Raises:
                ValueError: If the table is not found in available tables
            """
            # Derived tables are always valid
            if table_name in self._derived_tables:
                return

            # Check standard modules
            available_tables = self.list_tables()
            if table_name not in available_tables:
                raise ValueError(f"Table '{table_name}' is not supported. " f"Available tables: {', '.join(available_tables)}")


    ########################################################
    # pipeline/lakeflow_python_source.py
    ########################################################

    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]

        def read(self, partition):
            all_records = []
            if self.table_name == METADATA_TABLE:
                all_records = self._read_table_metadata()
            else:
                all_records, _ = self.lakeflow_connect.read_table(
                    self.table_name, None, self.options
                )

            rows = map(lambda x: parse_value(x, self.schema), all_records)
            return iter(rows)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        def __init__(self, options):
            self.options = options
            self.lakeflow_connect = LakeflowConnect(options)

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                # Assuming the LakeflowConnect interface uses get_table_schema, not get_table_details
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)  # pylint: disable=undefined-variable
